apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slackbot-server.fullname" . }}
  labels:
    {{- include "slackbot-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    llmarinerBaseUrl: {{ .Values.llmarinerBaseUrl }}
    modelId: {{ .Values.modelId }}
