apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slackbot-server.fullname" . }}
  labels:
    {{- include "slackbot-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slackbot-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slackbot-server.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: slackbot
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.slackTokenSecret.name }}
              key: {{ .Values.slackTokenSecret.key }}
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.slackAppTokenSecret.name }}
              key: {{ .Values.slackAppTokenSecret.key }}
        - name: LLMARINER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.llmarinerApiKeySecret.name }}
              key: {{ .Values.llmarinerApiKeySecret.key }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "slackbot-server.fullname" . }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
